### ISSUE TITLE
Only "Not Found" appears on the screen

### ISSUE THREAD

**Issue by Udirley** [staskobzar/amiws#1]
Hello

I am trying to use this service because in my current structure many sessions are opened and closed constantly and with a time the manager happens to refuse connections.
The installation and startup of amiws is done without any problems.
I chose not to use ssl.

Linux CentOS 6.0
Asterisk: 1.6.2.24
Asterisk server: 192.168.100.254
Amiws server: 192.168.100.251

The configuration file looks like this:

log_facility  : 40
log_level     : 6
ws_port       : 8000
web_root      : /var/www/amiws/web_root
auth_domain   : example.com
auth_file     : /var/www/.htaccess

amihosts:
  - name: ast01.example.com
    port: 5038
    host: 192.168.100.254
    username: teste
    secret: 123456
		
The connection is established with asterisk without problems.

amiws[6775]: AMI hosts connecting.
amiws[6775]: Listening Web Socket port 8000
amiws[6775]: Enabling HTTP Basic authentication.
amiws[6775]: AMI version: 1.1.0
amiws[6775]: AMI login with user: teste to server: ast01.example.com

The problem is that I can not access through port 8000.
In the first attempt to access the login screen appears, I enter the credentials, but only "Not Found" appears on the screen.

http://192.168.100.251:8000/

This appears when I try to access the browser:

amiws[6775]: New HTTP connection from 192.168.100.98:50833
amiws[6775]: Closed New Web Socket connection from 192.168.100.98:50833

Can anyone guide me?
Thank you very much in advance.

**Comment by staskobzar** [comment]
Hello,

You might need to check your directory "/var/www/amiws/web_root".
It should contain file "index.html" and the file should be readable by the user that runs amiws.

Does it works without basic authentication?

**Comment by Udirley** [comment]
Hello

Sorry for the delay in responding, I was still testing.
Before I had unpacked and installed in / usr / src, I reinstalled in / var / www and the problem was solved.
This application was exactly what I needed.

Thank you
