### ISSUE TITLE
Specific Command

### ISSUE THREAD

**Issue by Udirley** [staskobzar/amiws#2]
Hello

I noticed that the 'core show hints' command does not work.
All other commands work perfectly, only this one does not work.
I really need this command, is there anything I can do?

**Comment by staskobzar** [comment]
Hello,

Do you have something in logs?

**Comment by staskobzar** [comment]
Hello Udirley,

Yes, I see the problem. I will try to fix it soon.

**Comment by Udirley** [comment]
Okay, I'll wait for the correction. Thank you.

**Comment by staskobzar** [comment]
Hello Udirley,

I have fixed some command output handling issues. Please, try the latest changes from master branch.
Let me know if it works for you.

Thanks.

**Comment by Udirley** [comment]
Hello

I ran the tests and it worked correctly now.
Thank you again.
