### ISSUE TITLE
Constant disconnecting?

### ISSUE THREAD

**Issue by harrisonschultz** [staskobzar/amiws#24]
A couple questions

Trying to isolate an issue, I am having. I am using amiws with about 80 high traffic asterisk servers.  It seems be constantly reconnecting to some of them. Its likely something on my end, but I am trying to narrow it down. Do you know if this program does fine on that kind of load?

Is there some way to set an ID for each server instead of using the provided one? or maybe the hostname/ip instead? 
No worries if not.

Also thank you so much for this! Saved me so much time and effort. Wonderful program.

**Comment by staskobzar** [comment]
Hello,
I am not using it for couple years anymore and I never tried it with more then 5 asterisks.
I am glad to know it works on this number of high traffic servers.
If it happens only to some of the servers I would check NAT settings and network. If it's not crashing the application I guess the the AMI messages parsing is ok.

The internal networking library (mongoose) might be outdated too.

To set an id per server would take to update the code. I am not sure when I will be able to do it.
Good luck!

**Comment by harrisonschultz** [comment]
Sounds good!

Thanks for the quick response.
