### ISSUE TITLE
Multi-tenant Configuration

### ISSUE THREAD

**Issue by stalley** [staskobzar/amiws#3]
Is is possible to specify somewhere a global filter so that customer specific information is all that is returned? For example every queue, sip peer, etc begins with customer-XXXX. So customername-sales queue, or customername-100 for extensions.

**Comment by staskobzar** [comment]
Hello,

No. Filtering is not implemented. It only proxy the AMI traffic to web-socket. You can filter with your fron-end application only. 
As an option you can try to filter with Asterisk manager:
https://github.com/asterisk/asterisk/blob/master/configs/samples/manager.conf.sample#L94
