### ISSUE TITLE
config error  when put ./configure --with-ssl on debian 11 (bulllseye)

### ISSUE THREAD

**Issue by ringneck** [staskobzar/amiws#44]
Hi,

thank you for your greatjob!
here is log

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for ranlib... ranlib
checking for gcc... gcc
~~~~
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for yaml_parser_initialize in -lyaml... yes
checking for library containing CRYPTO_new_ex_data... -lcrypto
checking for library containing SSL_library_init... no

configure: error: openssl library not found  <--- how could i find ?

**Comment by staskobzar** [comment]
Hello @ringneck 
I have updated configure script.
Get the latest update and run ```./bootstrap``` first then try again ```./configure --with-ssl```
It should work

**Comment by ringneck** [comment]
Thank you ASAP !

**Comment by ringneck** [comment]
I try with ssl. 

it pass configure but, could not make

here is log

make[3]: Entering directory '/home/dipcast/amiws/src/lib'
gcc -DHAVE_CONFIG_H -I. -I../..  -DMG_ENABLE_SSL   -g -O2 -MT mongoose.o -MD -MP -MF .deps/mongoose.Tpo -c -o mongoose.o mongoose.c
mongoose.c: In function 'mg_mgr_free':
mongoose.c:2276:5: warning: implicit declaration of function 'FIPS_mode_set' [-Wimplicit-function-declaration]
 2276 |     FIPS_mode_set(0);
      |     ^~~~~~~~~~~~~
mongoose.c:2277:5: warning: implicit declaration of function 'CRYPTO_set_locking_callback' [-Wimplicit-function-declaration]
 2277 |     CRYPTO_set_locking_callback(NULL);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
mongoose.c:2278:5: warning: implicit declaration of function 'CRYPTO_set_id_callback' [-Wimplicit-function-declaration]
 2278 |     CRYPTO_set_id_callback(NULL);
      |     ^~~~~~~~~~~~~~~~~~~~~~
mongoose.c:2280:5: warning: implicit declaration of function 'ERR_remove_state' [-Wimplicit-function-declaration]
 2280 |     ERR_remove_state(0);
      |     ^~~~~~~~~~~~~~~~
mongoose.c:2282:5: warning: implicit declaration of function 'SSL_COMP_free_compression_methods' [-Wimplicit-function-declaration]
 2282 |     SSL_COMP_free_compression_methods();
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mongoose.c:2284:5: warning: implicit declaration of function 'ENGINE_cleanup' [-Wimplicit-function-declaration]
 2284 |     ENGINE_cleanup();
      |     ^~~~~~~~~~~~~~
mongoose.c:2286:5: warning: implicit declaration of function 'CONF_modules_free' [-Wimplicit-function-declaration]
 2286 |     CONF_modules_free();
      |     ^~~~~~~~~~~~~~~~~
mongoose.c:2287:5: warning: implicit declaration of function 'CONF_modules_unload' [-Wimplicit-function-declaration]
 2287 |     CONF_modules_unload(1);
      |     ^~~~~~~~~~~~~~~~~~~
mongoose.c:2289:5: warning: implicit declaration of function 'COMP_zlib_cleanup' [-Wimplicit-function-declaration]
 2289 |     COMP_zlib_cleanup();
      |     ^~~~~~~~~~~~~~~~~
mongoose.c:2291:5: warning: implicit declaration of function 'ERR_free_strings' [-Wimplicit-function-declaration]
 2291 |     ERR_free_strings();
      |     ^~~~~~~~~~~~~~~~
mongoose.c:2292:5: warning: implicit declaration of function 'EVP_cleanup' [-Wimplicit-function-declaration]
 2292 |     EVP_cleanup();
      |     ^~~~~~~~~~~
mongoose.c:2294:5: warning: implicit declaration of function 'CRYPTO_cleanup_all_ex_data' [-Wimplicit-function-declaration]
 2294 |     CRYPTO_cleanup_all_ex_data();
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/mongoose.Tpo .deps/mongoose.Po
rm -f libmongoose.a

do i update files last mongoose.h mongoose.c from https://www.cesanta.com/ ?

**Comment by staskobzar** [comment]
@ringneck thanks for the feedback. I am closing the issue
have a good day!
