### ISSUE TITLE
Sending multiple Variable in Originate and other supported AMI actions

### ISSUE THREAD

**Issue by Shkiperon** [staskobzar/amiws#59]
Is it possible to send multiple 'Variable' key in 'Originate' and other AMI actions that supports this functionality?
I've tried three ways:
1) Make long string for 'Variable' key
```
"var1=some1\r\nVariable: var2=some2\r\nVariable: var3=some3"
```
2) Make included JSON-object for 'Variable' key
```
{
  "var1": "some1",
  "var2": "some2",
  "var3": "some3"
}
```
3)  Make included list of vars for 'Variable' key
```
[
  "var1=some1",
  "var2=some2",
  "var3=some3"
]
```

In first case on Asterisk side I see only first variable with "modified tail" - "some1rnVariable: var2=some2rnVariable: var3=some3".
In second and third cases I see empty variables.

I want to send multiple variables to Asterisk without extra manipulations on Asterisk side.

**Comment by staskobzar** [comment]
@Shkiperon unfortunately, not possible right now.
I will have to update the code. Not sure how soon I will be able to do it
