### ISSUE TITLE
Originate Action causes hang for events

### ISSUE THREAD

**Issue by chrisnormand** [staskobzar/amiws#68]
Hy, I know that you stopped developping this great project but may be you will give me a hint about an issue I encountered.

When I call "Originate" action, events seems to be stacked and sent only once the endpoint answer the incoming call. 
So I am not imediatly aware of "NewChannel" event.

Would you have any idea on this case ?

Regards.
Chris.

**Comment by staskobzar** [comment]
Hi @chrisnormand 
I was sure that NewChannel is supposed to start immediatly when start calling.
Maybe to set "Asyn" header to "true" in the "Originate" action.
But I would say it is something in dialplan, maybe

**Comment by chrisnormand** [comment]
Hi staskobzar, thx for you quick reply
I have done new tests, directly on AMI with telnet, after 'Originate' ti waits until the endpoint answer to send 'Response: success' followed by the missing events. So it must not be linked with the gateway.
I see no option for Asyn for the action (I've tried to add it but same issue).

**Comment by chrisnormand** [comment]
My bad, "Async":"True" did the trick !
(Originate blocks by default)
Thx you very much sir !
