### ISSUE TITLE
Problem Install

### ISSUE THREAD

**Issue by fabiotheo** [staskobzar/amiws#9]
i have a problem with instalation:

root@teste-painel-1:~/amiws# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for ranlib... ranlib
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for yaml_parser_initialize in -lyaml... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gawk... (cached) mawk
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Doxyfile
config.status: creating doc/Makefile
config.status: creating src/Makefile
config.status: creating src/lib/Makefile
config.status: creating test/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

root@teste-painel-1:~/amiws# make
make  all-recursive
make[1]: Entering directory '/root/amiws'
Making all in src
make[2]: Entering directory '/root/amiws/src'
Making all in lib
make[3]: Entering directory '/root/amiws/src/lib'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/amiws/src/lib'
make[3]: Entering directory '/root/amiws/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/root/amiws/src'
make[2]: Leaving directory '/root/amiws/src'
Making all in test
make[2]: Entering directory '/root/amiws/test'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/amiws/test'
make[2]: Entering directory '/root/amiws'
make[2]: Leaving directory '/root/amiws'
make[1]: Leaving directory '/root/amiws'

**Comment by staskobzar** [comment]
try to run ```./bootstrap``` script before ```./configure```

**Comment by fabiotheo** [comment]
same problem...

root@teste-painel-1:~/amiws# make
make  all-recursive
make[1]: Entering directory '/root/amiws'
Making all in src
make[2]: Entering directory '/root/amiws/src'
Making all in lib
make[3]: Entering directory '/root/amiws/src/lib'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/amiws/src/lib'
make[3]: Entering directory '/root/amiws/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/root/amiws/src'
make[2]: Leaving directory '/root/amiws/src'
Making all in test
make[2]: Entering directory '/root/amiws/test'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/amiws/test'
make[2]: Entering directory '/root/amiws'
make[2]: Leaving directory '/root/amiws'
make[1]: Leaving directory '/root/amiws'

**Comment by staskobzar** [comment]
try to reset repo:
```git checkout .```
or re-clone to make sure you do not have any files generated with previous try. Then
```
./bootstrap
./configure
make
sudo make install
```

**Comment by fabiotheo** [comment]
i re-cloned him, but i had the same problem...

root@teste-painel-1:~/amiws# make
make  all-recursive
make[1]: Entering directory '/root/amiws'
Making all in src
make[2]: Entering directory '/root/amiws/src'
Making all in lib
make[3]: Entering directory '/root/amiws/src/lib'
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT mongoose.o -MD -MP -MF .deps/mongoose.Tpo -c -o mongoose.o mongoose.c
mv -f .deps/mongoose.Tpo .deps/mongoose.Po
rm -f libmongoose.a
ar cru libmongoose.a mongoose.o 
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libmongoose.a
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT frozen.o -MD -MP -MF .deps/frozen.Tpo -c -o frozen.o frozen.c
mv -f .deps/frozen.Tpo .deps/frozen.Po
rm -f libfrozen.a
ar cru libfrozen.a frozen.o 
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libfrozen.a
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT amipack.o -MD -MP -MF .deps/amipack.Tpo -c -o amipack.o amipack.c
mv -f .deps/amipack.Tpo .deps/amipack.Po
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT amipack_parser_detect.o -MD -MP -MF .deps/amipack_parser_detect.Tpo -c -o amipack_parser_detect.o amipack_parser_detect.c
mv -f .deps/amipack_parser_detect.Tpo .deps/amipack_parser_detect.Po
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT amipack_parser_prompt.o -MD -MP -MF .deps/amipack_parser_prompt.Tpo -c -o amipack_parser_prompt.o amipack_parser_prompt.c
mv -f .deps/amipack_parser_prompt.Tpo .deps/amipack_parser_prompt.Po
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT amipack_parser_message.o -MD -MP -MF .deps/amipack_parser_message.Tpo -c -o amipack_parser_message.o amipack_parser_message.c
mv -f .deps/amipack_parser_message.Tpo .deps/amipack_parser_message.Po
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT amipack_parser_command.o -MD -MP -MF .deps/amipack_parser_command.Tpo -c -o amipack_parser_command.o amipack_parser_command.c
mv -f .deps/amipack_parser_command.Tpo .deps/amipack_parser_command.Po
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT amipack_parser_queue.o -MD -MP -MF .deps/amipack_parser_queue.Tpo -c -o amipack_parser_queue.o amipack_parser_queue.c
mv -f .deps/amipack_parser_queue.Tpo .deps/amipack_parser_queue.Po
rm -f libamipack.a
ar cru libamipack.a amipack.o amipack_parser_detect.o amipack_parser_prompt.o amipack_parser_message.o amipack_parser_command.o amipack_parser_queue.o 
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libamipack.a
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT amiws_lib.o -MD -MP -MF .deps/amiws_lib.Tpo -c -o amiws_lib.o amiws_lib.c
mv -f .deps/amiws_lib.Tpo .deps/amiws_lib.Po
rm -f libamiws.a
ar cru libamiws.a amiws_lib.o 
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libamiws.a
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT config.o -MD -MP -MF .deps/config.Tpo -c -o config.o config.c
mv -f .deps/config.Tpo .deps/config.Po
gcc -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT config_parser.o -MD -MP -MF .deps/config_parser.Tpo -c -o config_parser.o config_parser.c
mv -f .deps/config_parser.Tpo .deps/config_parser.Po
rm -f libamiwscfg.a
ar cru libamiwscfg.a config.o config_parser.o 
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libamiwscfg.a
make[3]: Leaving directory '/root/amiws/src/lib'
make[3]: Entering directory '/root/amiws/src'
gcc -DHAVE_CONFIG_H -I. -I..    -Ilib -g -O2 -MT amiws-amiws.o -MD -MP -MF .deps/amiws-amiws.Tpo -c -o amiws-amiws.o `test -f 'amiws.c' || echo './'`amiws.c
mv -f .deps/amiws-amiws.Tpo .deps/amiws-amiws.Po
gcc -Ilib -g -O2   -o amiws amiws-amiws.o -Llib -lamiws -lmongoose -lfrozen -lamipack -lamiwscfg -lyaml 
make[3]: Leaving directory '/root/amiws/src'
make[2]: Leaving directory '/root/amiws/src'
Making all in test
make[2]: Entering directory '/root/amiws/test'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/amiws/test'
make[2]: Entering directory '/root/amiws'
make[2]: Leaving directory '/root/amiws'
make[1]: Leaving directory '/root/amiws'

**Comment by staskobzar** [comment]
I do not see any problem or errors.
What is the problem?

**Comment by fabiotheo** [comment]
sorry, it's fine now, thanks.


============================================================================
Testsuite summary for amiws 2.2.1
============================================================================
# TOTAL: 78
# PASS:  78
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/root/amiws/test'
make[2]: Leaving directory '/root/amiws/test'
make[1]: Leaving directory '/root/amiws/test'
make[1]: Entering directory '/root/amiws'
make[1]: Leaving directory '/root/amiws'
